# Generated by Django 6.0.4 on 2026-04-27 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(default='Attestation de scolarité', max_length=100)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('acceptée', 'Acceptée'), ('refusée', 'Refusée')], default='en attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('pdf', models.FileField(blank=True, upload_to='attestations/')),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('beneficiaire', 'Bénéficiaire'), ('agent', 'Agent Administratif'), ('admin', 'Administrateur')], default='beneficiaire', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.utilisateur'),
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.utilisateur')),
            ],
        ),
    ]
