# Generated by Django 6.0.4 on 2026-05-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_demande_annee_universitaire_demande_cin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('validation', 'Validation demande'), ('rejet', 'Rejet demande'), ('generation_pdf', 'Génération PDF'), ('soumission', 'Soumission demande'), ('register', 'Inscription')], max_length=50)),
                ('detail', models.TextField(blank=True, default='')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.utilisateur')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
