# Generated by Django 6.0.4 on 2026-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_journalaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='statut',
            field=models.CharField(choices=[('valide', 'Valide'), ('annulee', 'Annulée')], default='valide', max_length=20),
        ),
    ]
