# Generated by Django 6.0.4 on 2026-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_attestation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalaction',
            name='action',
            field=models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('validation', 'Validation'), ('rejet', 'Rejet'), ('generation_pdf', 'PDF'), ('soumission', 'Soumission'), ('register', 'Inscription')], max_length=50),
        ),
    ]
