# Generated by Django 6.0.4 on 2026-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_journalaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='motif_refus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
