# Generated by Django 6.0.4 on 2026-06-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_demande_motif_refus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantDB',
            fields=[
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20)),
                ('date_naissance', models.CharField(max_length=20)),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('filiere', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_universitaire', models.CharField(max_length=20)),
                ('annee_debut', models.CharField(max_length=10)),
                ('annee_fin', models.CharField(max_length=10)),
                ('nationalite', models.CharField(default='Marocaine', max_length=50)),
            ],
        ),
    ]
