# Generated by Django 6.0.4 on 2026-06-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_etudiantdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
