# Generated by Django 6.0.4 on 2026-06-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_utilisateur_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiantdb',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
